id = "gruvbox-material-mix"
name = "Gruvbox Material Mix"
version = "1.0.1"
schema_version = 1
authors = ["hyperdevstuff <harshch.work@proton.me>"]
description = "Gruvbox Material Port for Zed with more weights and styles."
repository = "https://github.com/hyperdevstuff/zed-gruvbox-material"
